name: Register Deployed Artifact

on: [workflow_dispatch]
  
jobs:
  run-register-build-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Register Deployed Artifact
        id: deployment
        uses: cloudbees-io-gha/register-deployed-artifact@CBP-31240
        with:
          artifact-id: 87ace777-ab20-4867-ac3f-ad5c28f46a29
          target-environment: preprod
          labels: testing, local                